### PR TITLE
Fixes to generic and Nthgen entries.

### PR DESCRIPTION
**Pull request by gnarancic**
Adding missing values for armours, weapons, equipment in generic and Nthgen entries.

### CODE REVIEW

**Comment by DanieleSuppo** [comment]
Thanks for the contribution!
I merged your changes into master, in case of further updates could you please remember to increase the revision number of the catalog you are gonna change, so Battlescribe does know that a new version is available?

Regards
Daniele

**Comment by gnarancic** [comment]
No problem, glad to help. I may work some more on it - after I read
instructions on how to write things for BattleScribe, that's why I didn't
increase the catalog value, I didn't know I should 🙈

On another note, do you know Zone Raiders are no longer available on
BattleScribe Appspot for some reason?
http://battlescribedata.appspot.com/#/repos

**Comment by DanieleSuppo** [comment]
Uh no I didn't know, current pandemic situation stopped my games so I didn't use Battlescribe so much.
Let me ask on Discord, I see if they can restore it, thanks for letting me know!

**Comment by gnarancic** [comment]
No problem, glad I could help! :) Completely understandable.

**Pull request merged**
